/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as HarisFalasRouteImport } from './routes/haris-falas'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrainingIntelligenceRouteImport } from './routes/training-intelligence'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedLogbookRouteImport } from './routes/_authenticated/logbook'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedQuestionnaireRouteImport } from './routes/_authenticated/questionnaire'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminExerciseLibraryRouteImport } from './routes/admin.exercise-library'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as AuthenticatedPlansSessionIdRouteImport } from './routes/_authenticated/plans.$sessionId'
import { Route as AuthenticatedWorkoutWorkoutIdRouteImport } from './routes/_authenticated/workout.$workoutId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const HarisFalasRoute = HarisFalasRouteImport.update({
  id: '/haris-falas',
  path: '/haris-falas',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIntelligenceRoute = TrainingIntelligenceRouteImport.update({
  id: '/training-intelligence',
  path: '/training-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogbookRoute = AuthenticatedLogbookRouteImport.update({
  id: '/logbook',
  path: '/logbook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestionnaireRoute =
  AuthenticatedQuestionnaireRouteImport.update({
    id: '/questionnaire',
    path: '/questionnaire',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExerciseLibraryRoute = AdminExerciseLibraryRouteImport.update({
  id: '/admin/exercise-library',
  path: '/admin/exercise-library',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlansSessionIdRoute =
  AuthenticatedPlansSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedPlansRoute,
  } as any)
const AuthenticatedWorkoutWorkoutIdRoute =
  AuthenticatedWorkoutWorkoutIdRouteImport.update({
    id: '/workout/$workoutId',
    path: '/workout/$workoutId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/haris-falas': typeof HarisFalasRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/training-intelligence': typeof TrainingIntelligenceRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/logbook': typeof AuthenticatedLogbookRoute
  '/plans': typeof AuthenticatedPlansRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/questionnaire': typeof AuthenticatedQuestionnaireRoute
  '/admin/exercise-library': typeof AdminExerciseLibraryRoute
  '/admin/': typeof AdminIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/plans/$sessionId': typeof AuthenticatedPlansSessionIdRoute
  '/workout/$workoutId': typeof AuthenticatedWorkoutWorkoutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/haris-falas': typeof HarisFalasRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/training-intelligence': typeof TrainingIntelligenceRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/logbook': typeof AuthenticatedLogbookRoute
  '/plans': typeof AuthenticatedPlansRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/questionnaire': typeof AuthenticatedQuestionnaireRoute
  '/admin/exercise-library': typeof AdminExerciseLibraryRoute
  '/admin': typeof AdminIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/plans/$sessionId': typeof AuthenticatedPlansSessionIdRoute
  '/workout/$workoutId': typeof AuthenticatedWorkoutWorkoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/haris-falas': typeof HarisFalasRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/training-intelligence': typeof TrainingIntelligenceRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/logbook': typeof AuthenticatedLogbookRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/questionnaire': typeof AuthenticatedQuestionnaireRoute
  '/admin/exercise-library': typeof AdminExerciseLibraryRoute
  '/admin/': typeof AdminIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/_authenticated/plans/$sessionId': typeof AuthenticatedPlansSessionIdRoute
  '/_authenticated/workout/$workoutId': typeof AuthenticatedWorkoutWorkoutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/glossary'
    | '/haris-falas'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/training-intelligence'
    | '/coach'
    | '/logbook'
    | '/plans'
    | '/profile'
    | '/progress'
    | '/questionnaire'
    | '/admin/exercise-library'
    | '/admin/'
    | '/tools/'
    | '/plans/$sessionId'
    | '/workout/$workoutId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/glossary'
    | '/haris-falas'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/training-intelligence'
    | '/coach'
    | '/logbook'
    | '/plans'
    | '/profile'
    | '/progress'
    | '/questionnaire'
    | '/admin/exercise-library'
    | '/admin'
    | '/tools'
    | '/plans/$sessionId'
    | '/workout/$workoutId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/glossary'
    | '/haris-falas'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/training-intelligence'
    | '/_authenticated/coach'
    | '/_authenticated/logbook'
    | '/_authenticated/plans'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/questionnaire'
    | '/admin/exercise-library'
    | '/admin/'
    | '/tools/'
    | '/_authenticated/plans/$sessionId'
    | '/_authenticated/workout/$workoutId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  GlossaryRoute: typeof GlossaryRoute
  HarisFalasRoute: typeof HarisFalasRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrainingIntelligenceRoute: typeof TrainingIntelligenceRoute
  AdminExerciseLibraryRoute: typeof AdminExerciseLibraryRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haris-falas': {
      id: '/haris-falas'
      path: '/haris-falas'
      fullPath: '/haris-falas'
      preLoaderRoute: typeof HarisFalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-intelligence': {
      id: '/training-intelligence'
      path: '/training-intelligence'
      fullPath: '/training-intelligence'
      preLoaderRoute: typeof TrainingIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logbook': {
      id: '/_authenticated/logbook'
      path: '/logbook'
      fullPath: '/logbook'
      preLoaderRoute: typeof AuthenticatedLogbookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questionnaire': {
      id: '/_authenticated/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof AuthenticatedQuestionnaireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exercise-library': {
      id: '/admin/exercise-library'
      path: '/admin/exercise-library'
      fullPath: '/admin/exercise-library'
      preLoaderRoute: typeof AdminExerciseLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plans/$sessionId': {
      id: '/_authenticated/plans/$sessionId'
      path: '/$sessionId'
      fullPath: '/plans/$sessionId'
      preLoaderRoute: typeof AuthenticatedPlansSessionIdRouteImport
      parentRoute: typeof AuthenticatedPlansRoute
    }
    '/_authenticated/workout/$workoutId': {
      id: '/_authenticated/workout/$workoutId'
      path: '/workout/$workoutId'
      fullPath: '/workout/$workoutId'
      preLoaderRoute: typeof AuthenticatedWorkoutWorkoutIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedPlansRouteChildren {
  AuthenticatedPlansSessionIdRoute: typeof AuthenticatedPlansSessionIdRoute
}

const AuthenticatedPlansRouteChildren: AuthenticatedPlansRouteChildren = {
  AuthenticatedPlansSessionIdRoute: AuthenticatedPlansSessionIdRoute,
}

const AuthenticatedPlansRouteWithChildren =
  AuthenticatedPlansRoute._addFileChildren(AuthenticatedPlansRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedLogbookRoute: typeof AuthenticatedLogbookRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedQuestionnaireRoute: typeof AuthenticatedQuestionnaireRoute
  AuthenticatedWorkoutWorkoutIdRoute: typeof AuthenticatedWorkoutWorkoutIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedLogbookRoute: AuthenticatedLogbookRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedQuestionnaireRoute: AuthenticatedQuestionnaireRoute,
  AuthenticatedWorkoutWorkoutIdRoute: AuthenticatedWorkoutWorkoutIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  GlossaryRoute: GlossaryRoute,
  HarisFalasRoute: HarisFalasRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrainingIntelligenceRoute: TrainingIntelligenceRoute,
  AdminExerciseLibraryRoute: AdminExerciseLibraryRoute,
  AdminIndexRoute: AdminIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
